version: "3.4"
services:
    nginx:
        image: nginx:1.25-alpine
        volumes:
            - ./docker/nginx/templates:/etc/nginx/templates:ro
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./data:/var/www/data:ro
        depends_on:
            - imgproxy
        ports:
            - 127.0.0.1:${NGINX_PORT:-80}:80
        env_file:
            - .env

    minio:
        image: minio/minio:RELEASE.2023-06-29T05-12-28Z
        volumes:
            - ./data:/data:rw
        ports:
            - 127.0.0.1:${MINIO_S3_PORT:-9000}:9000
            - 127.0.0.1:${MINIO_CONSOLE_PORT:-9001}:9001
        command: server /data --console-address ":9001"
        env_file:
            - .env

    imgproxy:
        image: darthsim/imgproxy:v3.18
        volumes:
            - ./data:/data:ro
            - ./presets.example.conf:/etc/presets.conf:ro
        command: ["imgproxy", "-presets", "/etc/presets.conf"]
        env_file:
            - .env
